
name: Security issue
description: File a bug report.
title: "[Secrurizy issue]: "
assignees:
body:
 - type: dropdown
    id: Scope
    attributes:
      label: How is the scope of the secruity issue 
      multiple: true
      options:
        -  insicnaiftant
        - smol
        -  Medeium
        - large 
        - Holy Fuck 
  validations:
    required: true
